"use strict";

module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 12,
    fontFamily:
      '"JetBrains Mono", "FiraCode Nerd Font", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1,
    letterSpacing: 0,
    cursorShape: "BLOCK",
    cursorBlink: false,
    css: ".header_appTitle,.header_windowControls  {opacity:0;visibility: hidden;} .header_hamburgerMenuLeft { opacity: 0}.terms_termsNotShifted.jsx-3986690196 { margin-top: 0;}",

    termCSS: "",
    workingDirectory: "",
    showHamburgerMenu: "",
    showWindowControls: "",
    padding: "10px 14px 5px",
    borderColor: "#333",

    backgroundColor: "#242431",
    foregroundColor: "#cdd6f4",
    selectionColor: "#585b70",
    cursorColor: "#f5e0dc",
    cursorAccentColor: "#11111b",
    colors: {
      black: "#45475A",
      blue: "#89b4fa",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      lightBlack: "#585b70",
      lightWhite: "#a6adc8",
      lightBlue: "#89b4fa",
      lightRed: "#f38ba8",
      lightGreen: "#a6e3a1",
      lightYellow: "#f9e2af",
      lightMagenta: "#f5c2e7",
      lightCyan: "#94e2d5",
    },

    shell: "C:/Program Files/Git/bin/bash.exe",
    shellArgs: ["-i"],
    env: {},
    bell: false,
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
    webLinksActivationKey: "",
    disableLigatures: true,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,
  },

  plugins: ["hyper-opacity", "hyper-pane"],
  localPlugins: [],
  keymaps: {
    "window:toggleFullScreen": "alt+enter",
  },
};
